name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "Srik212"
          git config --global user.email "srik120299@gmail.com"

      - name: Push changes to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote add gitlab https://${GITLAB_TOKEN}@${GITLAB_REPO#https://}
          git push --force gitlab main
