name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "Srik212"
          git config --global user.email "srik120299@gmail.com"

       - name: Add GitLab remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/sriyan02/VIA_DevSecOps_Project.git

      - name: Fetch GitLab branch and reset local branch
        run: |
          git fetch gitlab main
          git reset --hard origin/main

      - name: Push changes to GitLab
        run: |
          git push --force gitlab main
