name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror-bot@example.com"

      - name: Add GitLab remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/sriyan02/VIA_DevSecOps_Project.git

      - name: Fetch GitLab branch (if exists)
        continue-on-error: true
        run: |
          git fetch gitlab main || true

      - name: Force push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push --force gitlab main
